name: Comment on Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'Greetings! This is an automated message from GitHub Actions. :robot:\nYour pull request has been received and is awaiting for a review by the repository owner or a maintainer. This will take some time, so please be patient.\nWhile you wait, you can continue to work on other issues or pull requests, or explore the project further. Or you can simply relax and enjoy your day.\nThank you for your contribution to this project! You are awesome! :star:'
            })